#!/usr/bin/ruby

STDERR.print <<EOS
Warning: Ruby版本Homebrew安装脚本已被废弃，新版脚本使用Bash重写。
请使用以下命令:
  /bin/bash -c "$(curl -fsSL https://gitee.com/ineo6/homebrew-install/raw/master/install.sh)"

EOS

Kernel.exec "/bin/bash", "-c", '/bin/bash -c "$(curl -fsSL https://gitee.com/ineo6/homebrew-install/raw/master/install.sh)"'
